config/routes.rb
MattJones::Application.routes.draw do
  
  devise_for :users

  resources :rides do
    get "delete"
  end

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  root 'static_pages#home'

  get 'static_pages/home'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true
  attribute :ride_times, type: Array, default: []

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Nebraska Swoop",
      :to => "jayhopheli@gmail.com",
      :from => %("#{name}" <#{email}>),
      :'reply_to' => %(#{email})
    }
  end
end

app/models/ride.rb
class Ride < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :message, :nickname, ride_times: [])
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :set_ride, only: [:show, :edit, :update, :destroy]

  respond_to :html, :js

  def index
    @rides = Ride.all
  end

  def show
    @ride = Ride.find(params[:id])
  end

  def new
    @ride = Ride.new
  end

  def edit
    @ride = Ride.find(params[:id])
  end

  def create
    @ride = Ride.new(ride_params)

    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
        format.json { render :show, status: :created, location: @ride }
      else
        format.html { render :new }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to rides_url, notice: 'Ride was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride
      @ride = Ride.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ride_params
      params.require(:ride).permit(:roundtrip, :time_start, :time_end)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @rides = Ride.all
    @startTimes = @rides.pluck(:time_start)
    @uniqTimes = @startTimes.uniq

    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
      redirect_to :home
    else
      flash.now[:error] = 'Cannot send message.'
      render :home
    end
  end

  def submit_rides
    @rides = Ride.find(params[:ride_ids])
    @selections = []
    @rides.each do |r|
      @selections.push ride.time_start
    end
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper

  def datetime_to_natural(datetime)
    date = datetime.to_date.strftime("%B%e")
    time = datetime.to_time.strftime("%l:%M")    

    "#{date}th -#{time}"
  end

  def dates_natural(dates)
    natural_dates = []

    dates.each do |d|
      natural_dates.push datetime_to_natural(d)
    end
    
    natural_dates.each {|date| puts date}
  end

end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  Dates = []

  def rideDate (ride)
    ride.time_start.to_date.strftime("%B %e")
  end

  def getDates 
    @rides.each do |r|
      Dates.push rideDate(r)
    end
    Dates.uniq
  end
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class='content container'>
  <div align="center">
    <h3>Send A message to Us</h3>

    <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
      <%= f.input :name, :required => true %>
      <%= f.input :email, :required => true %>
      <%= f.input :message, :as => :text, :required => true %>
      <div class= "hidden">
	<%#= f.input :rides %>
	<%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
      <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<ul>
  <li><%= link_to 'Rides', rides_path %></li>
  <li><%= link_to 'New Ride', new_ride_path %></li>
  <li><%= link_to 'Home', root_path %></li>
</ul>

app/views/layouts/_header.html.erb
<span data-0='opacity:1;'
      data-500='opacity:0;'
      >
  <%= link_to image_tag('logo-red.png', class: 'logo'), root_path %>
</span>

<div id='menu'
     data-0='top:45%;'
     data-700='top:15%;'
     >

  <!--  <ul class="row"> -->
  <!--    <li class="span4"><%#= link_to 'Schedule', root_path %></li> -->
  <!--    <li class="span8"><%#= link_to 'Contact', contacts_path %></li> -->
  <!--    <%# if current_user %> -->
  <!--      <li><%#= link_to 'Sign Out', destroy_user_session_path, method: :delete %><!--</li> -->
  <!--    <%# else %> -->
  <!--      <li><%#= link_to 'Sign-Up', new_user_registration_path %></li> -->
  <!--      <li><%#= link_to 'Sign-In', new_user_session_path %></li> -->
  <!--    <%# end %> -->
  <!--    <%# if current_user.try(:admin?) %> -->
  <!--      <li><%#= link_to 'Rides', rides_path %></li> -->
  <!--    <%# end %> -->
  <!--    <li></li> -->
  <!--    <li></li> -->
  <!--  </ul> -->

  <div class="menu-nav row">
    <div><%= link_to 'Schedule', root_path %></div>
    <div><%= link_to 'Contact', contacts_path %></div>
    <% if current_user %>
      <div><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></div>
    <% else %>
      <div><%= link_to 'Sign-Up', new_user_registration_path %></div>
      <div><%= link_to 'Sign-In', new_user_session_path %></div>
    <% end %>
    <% if current_user.try(:admin?) %>
      <div><%= link_to 'Rides', rides_path %></div>
    <% end %>
    <div></div>
    <div></div>
  </div>
  <span data-0='opacity:0;'
	data-500='opacity:1;'
	>
    <%= link_to image_tag('logo-red.png', class: 'logo'), root_path %>
  </span>
  <h2 class='primary'
      data-0='opacity:0;'
      data-300='opacity:0.9;'
      >Nebraska Swoop
  </h2>

</div>

<div class='title'
     >
  <h3 class='pilot hidden'>
    Matthew Jones (Chief Pilot)
  </h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JayHop Helicopters</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>

    <div id="bg-img"></div>

    <div class=''>
      <%= render 'layouts/header' %>
      <p class='notice'><%= notice %></p>
      <p class='alert'><%= alert %></p>
    </div>

    <div id="skrollr-body">
      <div class="container">
	<%= yield %>
      </div>
    </div>

    <%#= render 'layouts/footer' %>

    <script>
     (function($){
       skrollr.init({
	 forceHeight: false,
	 smoothScrolling: false
       }).refresh();
     } (jQuery));
    </script>

  </body>
</html>

app/views/rides/_form.html.erb
<%= form_for(@ride) do |f| %>
  <% if @ride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
      <% @ride.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :roundtrip %><br>
    <%= f.check_box :roundtrip %>
  </div>
  <div class="field">
    <%= f.label :time_start %><br>
    <%= f.datetime_select :time_start %>
  </div>
  <div class="field">
    <%= f.label :time_end %><br>
    <%= f.datetime_select :time_end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rides/edit.html.erb
<div class='content container'>
  <h1>Editing ride</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @ride %> |
  <%= link_to 'Back', rides_path %>
</div>

app/views/rides/index.html.erb
<div id='ride-index' class='content container'>
  <h1>Jayhops</h1>
  <%= link_to 'Add a Ride', new_ride_path, class: 'hi-li' %>

  <table class="table">
    <thead>
      <tr>
	<th>Roundtrip</th>
	<th>Time start</th>
	<th>Time end</th>
	<th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @rides.each do |ride| %>
	<tr>
          <td><%= ride.roundtrip %></td>
          <td><%= ride.time_start %></td>
          <td><%= ride.time_end %></td>

          <td><%= link_to 'Edit', edit_ride_path(ride) %></td>
          <td><%= link_to 'Remove', ride, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr>
      <% end %>
    </tbody>
  </table>

  <br>


</div>

app/views/rides/new.html.erb
<div class='content container'>
  <h1>New ride</h1>

  <%= render 'form' %>

  <%= link_to 'Back', rides_path %>
</div>

app/views/rides/show.html.erb
<div class='content container'>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Roundtrip:</strong>
    <%= @ride.roundtrip %>
  </p>

  <p>
    <strong>Time start:</strong>
    <%= @ride.time_start %>
  </p>

  <p>
    <strong>Time end:</strong>
    <%= @ride.time_end %>
  </p>

  <%= link_to 'Edit', edit_ride_path(@ride) %> |
  <%= link_to 'Back', rides_path %>
</div>

app/views/static_pages/ajax-test.html.erb
<span style='position:absolute;top:0;left:20%;z-index:5;font-size:10vw;'>ajax test</span>

app/views/static_pages/home.html.erb
<h1 class='primary'
    data-0='opacity:0.9;'
    data-300='opacity:0;'
    >Nebraska Swoop</h1>
<div class='content'>
  <h2>
    Welcome to <strong>JayHop Helicopters</strong>: 
    Nebraska's only helicopter charter service, 
    home of the Nebraska Swoop, providing roundtrip 
    flights during University of Nebrasks sporting events. 
    Book your flight below!
  </h2>

  <%= image_tag('helicopter-flying.png', class: 'pic left') %>
  <%= image_tag('helicopter-seats.png', class: 'pic right') %>
 

  <div id='rides'
       data-0='opacity:0;'
       data-300='opacity:0.9;'
       >
    <%= simple_form_for @contact do |f| %>  

      <div class='ridetime'>
	<% getDates.each do |d| %>

	  <div id='date'>
	    <h3><%= d %></h3>
	  </div>

	  <% @rides.each do |ride| %>
	    <% @rideTime = ride.time_start.to_time.strftime("%l:%M") %>
	    <div id='time'>

	      <% if (rideDate(ride) == d) %>
		<%= @rideTime %>
		<% if ride.roundtrip == true %>
		  (roundtrip)
		<% end %>
		<%= check_box_tag "contact[ride_times][]", datetime_to_natural(ride.time_start) %>
	      <% end %>

	    </div>

	  <% end %>
	<% end %>
      </div>
    </div>

    <div id='ride-form'>

      <div class=''>
	<%= f.input :name, :required => true %>
      </div>
      <%= f.input :email, :required => true %>
      <%= f.input :message, :as => :text, :required => true %>

      <div class= "hidden">
	<%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
      <div>
	<%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
      </div>

    </div>
  <% end %>

</div>

<script>
</script>